version: '3.5'
services:
  db:
    container_name: hocom_db
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_connections=1024
    env_file:
      - .env-db

  app:
    container_name: hocom_app
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8080:80'
      - '8081:443'
    volumes:
      - ./.:/app
    tmpfs:
      - /app/runtime
      - /app/web/assets
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env-app
    command: bash -c "chmod -R 777 /app/runtime /app/web/assets /app/web/uploads && composer install && php yii migrate --interactive=0 && supervisord -c /etc/supervisor/supervisord.conf"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8089:8080"